import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
    server: {
        port: 5174,
        strictPort: true,
    },
    plugins: [
        react(),
        tailwindcss(),
        VitePWA({
            registerType: "autoUpdate",
            devOptions: {
                enabled: true,
            },
            workbox: {
                // Activate the new SW immediately without waiting for all tabs to close.
                skipWaiting: true,
                // Take control of all existing clients as soon as the SW activates.
                clientsClaim: true,
                // Remove precache entries generated by older builds to avoid stale asset serving.
                cleanupOutdatedCaches: true,
                // Serve index.html for any navigation request not matched by a precached asset,
                // which is required for client-side routing (React Router) to work offline.
                navigateFallback: "/index.html",
                importScripts: ["/service-worker/push.js"],
            },
            includeAssets: ["icon-192.png", "icon-512.png", "15.png"],
            manifest: {
                name: "On fête nos 15 ans !",
                short_name: "15 ans 🩷",
                start_url: "/save-the-date",
                display: "standalone",
                background_color: "#ffffff",
                theme_color: "#000000",
                icons: [
                    {
                        src: "icon-192.png",
                        sizes: "192x192",
                        type: "image/png",
                    },
                    {
                        src: "icon-512.png",
                        sizes: "512x512",
                        type: "image/png",
                    },
                ],
            },
        }),
    ],
});
